### ISSUE TITLE
Could not connect from client

### ISSUE THREAD

**Issue by amebrahimi** [HirbodBehnam/MTProtoProxyCentOSInstall#1]
Hello and thank you for your work.
* I have run the script and I have a question what is the username good for?
* What is the AD_TAG good for?

And when I create a user and a key when I want to connect to it from the client it sees the mtproto server
but it cannot connect to it. it switches between connecting and online.
Is there any log which I could look at to see which see what is the problem is?

![image](https://user-images.githubusercontent.com/12514657/41703441-8560a540-7548-11e8-9af1-7628f3de2225.png)

![image](https://user-images.githubusercontent.com/12514657/41703456-993c2eae-7548-11e8-937d-f7de21f5983e.png)

**Comment by HirbodBehnam** [comment]
Usernames are just a name for each secret they DO NOT have any effect on the client. Also at logs, you will get connections count to each secret by Username.

AD Tag helps you setup promoted channel and getting status of your proxy at [MTBroxyBot](https://t.me/mtproxybot) (How many users from each country had been connected to your proxy). Set it up [here](https://t.me/mtproxybot)

Also report proxy related issues [here](https://github.com/alexbers/mtprotoproxy/issues) and you may have some problems if you are VPS provider is OVH or IPhoster.
If you think the problem is from my script just send the logs here. Get logs with `systemctl status mtprotoproxypython -l` command.

**Comment by amebrahimi** [comment]
WOW thank you for your quick response.
Nope, I don't think it's from your script I asked here because I just installed this script and it didn't work. I turned off the firewall and still no success.
Here is the log
```
╭─root@Family ~
╰─# systemctl status mtprotoproxypython -l
● mtprotoproxypython.service - MTProto Proxy Service
   Loaded: loaded (/etc/systemd/system/mtprotoproxypython.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-06-21 07:26:44 UTC; 4min 59s ago
 Main PID: 25090 (python3.6)
   CGroup: /system.slice/mtprotoproxypython.service
           └─25090 /usr/bin/python3.6 /opt/mtprotoproxy/mtprotoproxy.py

Jun 21 07:26:44 Family systemd[1]: Started MTProto Proxy Service.
Jun 21 07:26:44 Family systemd[1]: Starting MTProto Proxy Service...
Jun 21 07:26:45 Family python3.6[25090]: prince: tg://proxy?server=138.68.97.40&port=11443&secret=3157c82f5b8edab49657a1530a174bb4
```

**Comment by HirbodBehnam** [comment]
I'm not very sure why this thing happens but can you answer these questions:

- Did you use AD TAG?
- What is you VPS provider? (Digital Ocean I guess)
- Have you tried on different port? (Test it on 443)
- Did you tried other MTProto Proxy scripts?([Example](https://github.com/FreedomPrevails/JSMTProxy) or [Official One](https://github.com/TelegramMessenger/MTProxy))

**Comment by amebrahimi** [comment]
* Yes 
* Your guess was correct
* I have tried different ports (even 443)
* nope your script was my first try

**Comment by HirbodBehnam** [comment]
OK you can do 2 things:

1. Install another proxy script and try that one (I recommend you [JSMTProxy](https://github.com/FreedomPrevails/JSMTProxy). It does not support AD TAG. )
2. Open an issue [here](https://github.com/alexbers/mtprotoproxy/issues/) and tell it to the main proxy developer.

**Comment by amebrahimi** [comment]
Will do Thanks for your help

**Comment by amebrahimi** [comment]
Just for your knowllage JSMTProxy worked.

**Comment by HirbodBehnam** [comment]
So report this issue [here](https://github.com/alexbers/mtprotoproxy/issues/) and Also mention that you installed it with my proxy. It could be just an issue with my script.

**Comment by amebrahimi** [comment]
I'm on it

**Comment by HirbodBehnam** [comment]
Wait is your VPS behind a NAT?

**Comment by amebrahimi** [comment]
Hmm... Sorry, I am not quite sure. IP stuff is way beyond my knowledge

**Comment by HirbodBehnam** [comment]
OK nevermind

**Comment by HirbodBehnam** [comment]
Ok the script is updated.
