### ISSUE TITLE
install

### ISSUE THREAD

**Issue by ZarinNegah** [HirbodBehnam/MTProtoProxyCentOSInstall#2]
سلام

و آیا بهتر نیست کد های زیر را در ابتدا و قبل شروع نصب برای سنتوس 7 قرار دهید،چون در بعضی سرورها نصب و فعال نمی باشد

if [ ${OS} == CentOS ];then
  yum install firewalld -y
  systemctl enable firewalld
  systemctl start firewalld
  systemctl status firewalld
fi

**Comment by ZarinNegah** [comment]
همچنین در آخرش لینک پروکسی رو نشون نمیداد
ولی خودم دستی میزدم اوکی بود و کار میکرد

**Comment by ZarinNegah** [comment]
firewall-cmd --permanent --add-port=${uport}/tcp
firewall-cmd --permanent --add-port=${uport}/udp
firewall-cmd --reload

**Comment by HirbodBehnam** [comment]
Hello this project is exclusively designed for centos 7. Not any other Linux systems. Also you the script *may* fail to get you IP. And I've written in README.MD that you can get links with `systemctl status mtprotoproxy -l`

**Comment by ZarinNegah** [comment]
> 
> 
> Hello this project is exclusively designed for centos 7. Not any other Linux distributions. Also the script _may_ fail to get your IP. And I've also written in README.MD that you can get links with `systemctl status mtprotoproxy -l`
> Also my code automatically configures firewall.

server os is centos 7.5 64 bit

**Comment by HirbodBehnam** [comment]
I don't know what is the problem, you can always see logs and secrets by `systemctl status mtprotoproxy -l`. 
BTW maybe I change the code to use `curl` instead of `wget` when getting the IP.

**Comment by CraftedCat** [comment]
> server os is centos 7.5 64 bit

You did not believe me that the Iranian hoster blocks traffic? omg

**Comment by HirbodBehnam** [comment]
@ZarinNegah 
The @CraftedCat is right Iranian and Russian virtual server providers block telegram traffics. You must buy a server that is not located in either Iran or Russia.
