### ISSUE TITLE
关于代理限速的问题

### ISSUE THREAD

**Issue by ProfessorFake** [HirbodBehnam/MTProtoProxyCentOSInstall#3]
你好，感谢你的工作，我用你的脚本一键安装了MTProto代理，可以完美运行，但是很奇怪为什么会被限速，最高速度也才500K/s，而我的v2ray高峰速度为10M左右，所以很奇怪为什么会被限速，请问如何调整参数?
我从网上找别人分享的MTProto代理，速度也比我这个快，所以我觉得应该是哪个参数的问题，所以请教你如何调整，望告知，谢谢你！

是安全模式的问题吗？

**Comment by HirbodBehnam** [comment]
Hi
I used Google translate to translate your issue. I suggest to change TO_CLT_BUFSIZE in config file to higher value (Default is 16384). That should speed up your proxy but proxy will require more ram. 
Also a week CPU can cause slow uploads.

**Comment by ProfessorFake** [comment]
Sorry, I thought you are Chinese, so I submitted this issues in Chinese. It's my fault.
I change TO_CLT_BUFSIZE to higher value, but speed is not much improved. 
I don't know what to do, so reinstall [MTProxy](https://github.com/TelegramMessenger/MTProxy) manually. Now speed is better.

However I don't know the reason why speed is slow😓

Thanks for your quick reply!!!

**Comment by HirbodBehnam** [comment]
No problem. You can also ask about it at the proxy project issues.
[Issues](https://github.com/alexbers/mtprotoproxy)
