### ISSUE TITLE
فیلتر شدن سریع

### ISSUE THREAD

**Issue by AhmadNemati** [HirbodBehnam/MTProtoProxyCentOSInstall#5]
سلام دوست عزیز
روی هر دو نسخه تست کردم به سرعت ای پی فیلتر میشه ولی الان پروکسی هست یک ماه داره کار میکنه بدون تعویض ای پی و سرورش برای هتزنر هست به حالت کلی دامنه روی کلود فلیر هست ولی در صورتی که مسنقیم به ای پی وصل بشیم هم باز وصل میشه و بدون مشکل کار میکنه

**Comment by HirbodBehnam** [comment]
سلام در حال حاظر هم گفتم که من فقط این راه ها را بلد هستم که زود توسط دولت بسته می شوند.
متاسفانه من راه دیگری بلد نیستم.

**Comment by AhmadNemati** [comment]
به نظرتون سورس رو ادیت کردن؟

**Comment by HirbodBehnam** [comment]
درباره ی سورس های اختصاصی زیاد شنیدم مطمئن نیستم و نخریدم تا به حال.
