### ISSUE TITLE
بلاخره ی سورس درست حسابی پیداشد

### ISSUE THREAD

**Issue by Meytiz** [HirbodBehnam/MTProtoProxyCentOSInstall#50]
سلام 
دمت گرم کار کرد بعد 1 هفته گشتن سورس fake tls دار خوب 
erlang از  کار افتاده

**Comment by HirbodBehnam** [comment]
سلام خواهش میکنم
سورس erlang رو خود توسعه دهنده ش زده اسکریپتش و اصلا دست من نیست! توی خود repoش اگر یه issue باز کنید احتمالا بهتر باشه.
