### ISSUE TITLE
No Connected 

### ISSUE THREAD

**Issue by Angize** [HirbodBehnam/MTProtoProxyCentOSInstall#52]
Slm vaghti python script ro nasb mikonam kollan proxy vasl nmishe vali vaghti official script ro nasb mikonam moshkeli nadare 
moshkel kojast?

**Comment by HirbodBehnam** [comment]
سلام
میشه لطفا خروجی `systemctl status mtprotoproxy -l` رو بفرستید؟ دقت کنید که این لاگ ها حاوی لینک های پراکسی هستن برای همین اون خط هارو حذف کنید.

**Comment by HirbodBehnam** [comment]
Close due to inactivity.
