### ISSUE TITLE
Broken Install on Ubuntu 22.04

### ISSUE THREAD

**Issue by MadHundred** [HirbodBehnam/MTProtoProxyCentOSInstall#53]
Install is broken on ubuntu 22.04 , with `No module named _cffi_backend` error.
it seems on python 3.8 or 3.10 this module changed.

Solution :  [No module named _cffi_backend](https://stackoverflow.com/a/38594247/951440)

**Server:**
 - Server OS: Ubuntu 22.04

**Comment by HirbodBehnam** [comment]
Thanks for reporting this bug!
I'll try to fix it as soon as I can.
