### ISSUE TITLE
cant add 2 AD Tag for manage other secrets.

### ISSUE THREAD

**Issue by mahansalimi** [HirbodBehnam/MTProtoProxyCentOSInstall#55]
i am using updated version on Ubunto 18.04 but only can add one AD TAG

for example i made 2 proxy secrets ,when want add them to Telegram "**MTProxy Admin bot**" then will show an AD TAG and ask to add it to server.
then when i want to add second proxy secret to bot.will give me another AD TAG and software only accept one AD TAG for all secrets.
so finaly need to add option on software to ask from user that he is entering AD Tag for which secret. 
thanks for help

**Comment by HirbodBehnam** [comment]
Hello
Unfortunately this is not supported. All of the secrets you create for proxy will share the same secret.
If you really want to have different ad tag for each proxy, you have to manually launch the proxy with different configs and different ad tags.
