### ISSUE TITLE
When the latest version is in use, the agent is often unavailable. Can you provide the installation addresses of the next two versions?

### ISSUE THREAD

**Issue by asd307769162** [HirbodBehnam/MTProtoProxyCentOSInstall#56]
The script uses the latest version of the script. The server centos, debian, and ubantu have all tried it. In Apple's telegram client, after adding the mtproto proxy when downloading and logging in, the proxy displays "unavailable", and normally it should display ""xx"" The delay of ms is right; then the mtproto of my previous build number did not have this problem. I'm not sure if it's because of the new script. If it's convenient, can you provide the download addresses of the early 2-3 scripts, and I'll test it here. thanks

**Comment by HirbodBehnam** [comment]
Hello
Does it work with other clients? And does it work with an VPN? Also is the service on server running and up? If not can you send me the logs?
