### ISSUE TITLE
can't connect from Iran

### ISSUE THREAD

**Issue by m-rahmanzad** [HirbodBehnam/MTProtoProxyCentOSInstall#57]
hello sir thanks for such great script 
I ran this service into my servers some of them worked prefect but some of them didn't work
I checked firewall rule that was ok and I tested by hercules tool tcp client can connect to port successfully.
telegram gets stuck on connecting...
here this is my status of service respond , I renamed IP and user for privacy 

----------------------------------------------

>   root@??????:~# systemctl status mtprotoproxy -l
> ● mtprotoproxy.service - MTProto Proxy Service
>      Loaded: loaded (/etc/systemd/system/mtprotoproxy.service; enabled; vendor preset: enabled)
>      Active: active (running) since Mon 2022-10-17 03:29:44 UTC; 6min ago
>    Main PID: 18523 (python3)
>       Tasks: 5 (limit: 1131)
>      Memory: 17.8M
>      CGroup: /system.slice/mtprotoproxy.service
>              └─18523 /usr/bin/python3 /opt/mtprotoproxy/mtprotoproxy.py
> 
> Oct 17 03:29:44 ??????????? systemd[1]: Started MTProto Proxy Service.
> Oct 17 03:29:44 ??????????? python3[18523]: barboood: tg://proxy?server=???????????&port=7575&secret=ee27a62ab7d9ac42eb>
> Oct 17 03:29:44 ?????????? python3[18523]: Found uvloop, using it for optimal performance
> Oct 17 03:29:45 ?????????? python3[18523]: Got cert from the MASK_HOST www.cloudflare.com, its length is 1964

--------------------------------------------

Can you tell me Where am I doing wrong?

ps: I test it by vpn again but it doesn't work

**Comment by HirbodBehnam** [comment]
Hello
Does other sources work? For example does the official server works? Or the go one?

**Comment by m-rahmanzad** [comment]
> 
thanks for answer
.........................

Update:
 I reinstalled it and test by iphone it can connect but can't download anything and  it doesn't work on desktop telegram version at all but in some vpn application it work 
maybe  the government block  fake tls some how, mtproto doesn't work in some servers
