### ISSUE TITLE
cannot run MTProtoProxyInstall.sh . gave error line 138: syntax error 

### ISSUE THREAD

**Issue by farhiikhteh** [HirbodBehnam/MTProtoProxyCentOSInstall#6]
https://github.com/HirbodBehnam/MTProtoProxyCentOSInstall/blob/dc747e270fa6678e7bcfb25aed95e493af98bffd/MTProtoProxyInstall.sh#L138

**Comment by HirbodBehnam** [comment]
I can run the script on my VPS, whats you bash version? Get it with `--version`

**Comment by HirbodBehnam** [comment]
Also I can get this error when I'm running this with `sh`, can you try with `bash`?

**Comment by farhiikhteh** [comment]
with bash work well 
 version 4.2.4

**Comment by HirbodBehnam** [comment]
Good
