### ISSUE TITLE
Is it possible to query the data usage of each user?

### ISSUE THREAD

**Issue by asd307769162** [HirbodBehnam/MTProtoProxyCentOSInstall#60]
Since the script has "Change user quota options", it should be possible to count the traffic usage of all users. But I have tried various methods, but I can't find out how much traffic each user uses. Is there any way?

**Comment by HirbodBehnam** [comment]
Hello
From script, no it's not possible. But you can get the quota usage from logs of the proxy using `systemctl status mtprotoproxy -l`

**Comment by asd307769162** [comment]
I used "systemctl status mtprotoproxy -l", but it only shows the usage of the last 6 users, if I have 20 users, other users can't see it, can I list all users?

**Comment by HirbodBehnam** [comment]
You can use something like `journalctl --unit=mtprotoproxy -n 100 --no-pager` to get the last 100 lines.

**Comment by asd307769162** [comment]
Thanks, it's ok.
