### ISSUE TITLE
pythonMTP proxy becomes slow on recent connections

### ISSUE THREAD

**Issue by asd307769162** [HirbodBehnam/MTProtoProxyCentOSInstall#61]
It was working fine before, but started 4 days ago and suddenly all my python mtp proxies became very slow. The specific performance is as follows:
1. If the mobile phone has not used telegram for a long time, or put the telegram in the background of the mobile phone, and then switch to telegram, it will always display "connecting to the proxy", and it will take 8-10 seconds to become a normal connected state.
2. If it is connected, there is no problem with the speed during use. It is just that you have just switched to telegram from other applications, and you need to wait for 8-10 seconds. In the past, it didn't take so long, normally 2 seconds was enough.
3. Trying Android and Apple mobile phones in turn has this problem, and the computer version of telegram needs to wait longer.
4. I have tried using servers from different manufacturers, a total of 10, including centos and debian ubuntu. Manufacturers are mainly dmit, and aws.
5. Try other language versions of mtp proxy, but did not find this problem.
6. Location: China
Please take a look, thank you.

**Comment by HirbodBehnam** [comment]
Can you please report this problem in the repository for proxy itself instead of here?
I doubt it's because of the script. It's because of the proxy itself.
